### PR TITLE
twitch.tv: Fix player position

### PR DESCRIPTION
**Pull request by nikola-kocic**
Currently player is covered by chat, this makes player always visible

### CODE REVIEW

**Comment by sebaro** [comment]
I don't see it here, are you logged in? Can you post a screenshot?

**Comment by nikola-kocic** [comment]
Player is positioned wrong even when chat is hidden.

Linux, Firefox browser, VLC plugin, i3 WM

With hidden chat
With shown chat

**Comment by sebaro** [comment]
The problem is not the script, is the video plug-in that goes out of the player element borders.
For me is OK with VLC, but not with mozplugger/mpv.
Ihave to find a way to fix that. Your solution works for large screen but not for my 1280x1024 display.

screenshot-2015-07-15 22 05

**Comment by sebaro** [comment]
It seems to be working fine with "Alt" (second menu) which uses EMBED instead of OBJECT.

**Comment by nikola-kocic** [comment]
I can confirm that using "Alt", player is correctly centered but is too small on my resolution

twitch-small-auto

**Comment by sebaro** [comment]
Try this update:
http://isebaro.com/viewtube/include/files/viewtubeplus.user.js

**Comment by nikola-kocic** [comment]
Update fixed player position when chat is hidden but it's still shifted to the right when chat is shown.

twitch-bad-player-position-with-chat-update1
twitch-good-player-position-without-chat-update1

**Comment by sebaro** [comment]
I think that's the best I can do for now.
I have to find a way to check when the chat or the left menus are shown.

**Comment by sebaro** [comment]
Try the new update:
http://isebaro.com/viewtube/include/files/viewtubeplus.user.js

**Comment by nikola-kocic** [comment]
New update works great :) Thank you!

**Comment by sebaro** [comment]
OK, thanks.

**Pull request closed without merging**
